[package]
name = "Bluefairy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.4"
serde = "1.0"
serde_derive = "1.0"
rayon = "1.5.1"
mcts = "0.2"

[dev-dependencies]
criterion = "0.3"